language: php
php:
  - 7.1
install:
  - composer self-update
  - npm install --global node-sass
script: /bin/true

deploy:
  provider: script
  on:
    branch: master
  script: /bin/true
  skip_cleanup: true

before_deploy:
  - git config --file=.gitmodules submodule.output_prod.url https://$GH_TOKEN:@github.com/phprio/phprio.github.io.git
  - git submodule sync
  - git submodule update --init --recursive --remote
  - git config --global user.name "Travis-CI"
  - git config --global user.email "travis.ci@phprio.org"
  - composer install
  - composer prod-deploy
