# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.

title: PHPRio
subtitle: Grupo de Desenvolvedores PHP do Rio e Grande Rio

google_analytics_tracking_id: false

meses:
  - Janeiro
  - Fevereiro
  - Março
  - Abril
  - Maio
  - Junho
  - Julho
  - Agosto
  - Setembro
  - Outubro
  - Novembro
  - Dezembro

tag_descriptions:
  evento: Todos os eventos que organizamos.
  happy-hour: Os happy hours que nós organizamos, juntando a galera para um bate-papo mais descontraído.
  palestras: Nosso ciclo de palestras, trazendo novos tópicos para serem apresentados e discutidos pelo grupo.

links:
  telegram: https://telegram.me/phprio
  groups  : https://groups.google.com/forum/#!forum/phprio-org
  meetup  : https://meetup.com/PHP-Rio
  github  : https://github.com/PHPRio
  twitter : https://twitter.com/phprio
  facebook: https://www.facebook.com/PHPRio-160383237381004
  medium  : https://medium.com/phprio
  linkedin: https://www.linkedin.com/groups/1202577
  vagas   : https://docs.google.com/forms/d/e/1FAIpQLSfTP8OqAKkpcw3vO-a-cDk3Wrj4F8OGSlR4ewgIrBTJkRCeLw/viewform
